-- ═══════════════════════════════════════════════════════════════════
-- JobBoard Pro — Complete Supabase Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Safe to run multiple times (uses IF NOT EXISTS / IF EXISTS guards)
-- ═══════════════════════════════════════════════════════════════════

-- ─── Extensions ───────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── 1. JOBS TABLE ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS jobs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  updated_at    timestamptz DEFAULT timezone('utc', now()),
  user_id       uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  -- Core fields
  title         text NOT NULL,
  company       text NOT NULL,
  location      text,
  type          text DEFAULT 'Full-time'
                  CHECK (type IN ('Full-time','Part-time','Internship','Contract','Freelance')),
  salary        text,
  skills        text,
  source        text,
  applylink     text,

  -- Status & tracking
  status        text DEFAULT 'Bookmarked'
                  CHECK (status IN ('Bookmarked','Applied','Interview','Offer','Rejected','Withdrawn')),
  priority      text DEFAULT 'Medium'
                  CHECK (priority IN ('High','Medium','Low')),
  applieddate   text,
  deadline      text,
  notes         text,

  -- Auto-apply tracking
  auto_applied  boolean DEFAULT false,
  auto_applied_at timestamptz,
  auto_apply_method text,   -- 'email' | 'link'

  -- Match score (calculated client-side, stored for sorting)
  match_score   smallint DEFAULT 0 CHECK (match_score >= 0 AND match_score <= 100)
);

-- Add new columns to existing jobs table (safe — skips if column exists)
DO $$ BEGIN
  ALTER TABLE jobs ADD COLUMN updated_at    timestamptz DEFAULT timezone('utc', now()); EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE jobs ADD COLUMN auto_applied  boolean DEFAULT false;                      EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE jobs ADD COLUMN auto_applied_at timestamptz;                               EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE jobs ADD COLUMN auto_apply_method text;                                   EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE jobs ADD COLUMN match_score   smallint DEFAULT 0;                         EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ─── 2. PROFILES TABLE ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id               uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  created_at       timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  updated_at       timestamptz DEFAULT timezone('utc', now()),

  -- Personal
  full_name        text,
  email            text,
  phone            text,
  location         text,
  avatar_url       text,

  -- Professional
  headline         text,
  summary          text,
  skills           text,           -- comma-separated
  experience       text,
  education        text,
  certifications   text,
  languages        text,

  -- Links
  linkedin         text,
  github           text,
  portfolio        text,

  -- Job preferences
  target_roles     text,
  target_locations text,
  expected_salary  text,

  -- Resume data (last generated)
  resume_template  text DEFAULT 'professional',
  resume_data      jsonb,          -- full parsed resume JSON

  -- Settings (user-specific, stored server-side)
  report_email     text,
  auto_report      boolean DEFAULT false,
  report_time      text DEFAULT '09:00',
  report_format    text DEFAULT 'both',
  job_search_keywords   text,
  job_search_location   text,
  auto_job_search  boolean DEFAULT false,
  job_search_time  text DEFAULT '08:00',
  job_search_count text DEFAULT '50',
  job_search_format text DEFAULT 'both'
);

-- Add missing columns to existing profiles table
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN avatar_url text;           EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN resume_template text DEFAULT 'professional'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN resume_data jsonb;         EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN report_email text;         EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN auto_report boolean DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN report_time text DEFAULT '09:00'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN report_format text DEFAULT 'both'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN job_search_keywords text;  EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN job_search_location text;  EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN auto_job_search boolean DEFAULT false; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN job_search_time text DEFAULT '08:00'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN job_search_count text DEFAULT '50'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE profiles ADD COLUMN job_search_format text DEFAULT 'both'; EXCEPTION WHEN duplicate_column THEN NULL; END $$;

-- ─── 3. AUTO-APPLY LOG TABLE ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS auto_apply_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  job_id          bigint REFERENCES jobs(id) ON DELETE SET NULL,

  job_title       text,
  company         text,
  apply_method    text,           -- 'email' | 'link' | 'form'
  apply_target    text,           -- email address or URL
  status          text DEFAULT 'sent'
                    CHECK (status IN ('sent','failed','pending','acknowledged')),
  cover_letter    text,
  error_message   text,
  acknowledged_at timestamptz
);

-- ─── 4. SAVED SEARCHES TABLE ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_searches (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  label       text NOT NULL,
  keywords    text,
  location    text,
  job_type    text,
  category    text,
  salary_min  text,
  experience  text,
  last_used   timestamptz
);

-- ─── 5. JOB NOTES TABLE (rich notes per job) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS job_notes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  job_id      bigint REFERENCES jobs(id) ON DELETE CASCADE NOT NULL,
  note_type   text DEFAULT 'general'
                CHECK (note_type IN ('general','interview','follow_up','offer','rejection','cover_letter','prep')),
  content     text NOT NULL,
  is_pinned   boolean DEFAULT false
);

-- ─── 6. CALENDAR EVENTS TABLE ────────────────────────────────────────────────
-- Stores custom calendar events (reminders, follow-ups, phone screens, etc.)
-- Job-derived events (deadlines, applied dates) are computed client-side from
-- the jobs table, so they don't need to be stored here.
CREATE TABLE IF NOT EXISTS calendar_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  -- Optional link back to a specific job
  job_id      bigint REFERENCES jobs(id) ON DELETE SET NULL,

  -- Event data
  title       text NOT NULL,
  event_date  date NOT NULL,
  event_time  text,                         -- e.g. "14:30" (stored as text, displayed as-is)
  type        text DEFAULT 'reminder'
                CHECK (type IN ('deadline','interview','follow_up','reminder','offer','other')),
  notes       text,
  is_done     boolean DEFAULT false NOT NULL
);

-- Add profiles.projects column (stores resume projects as JSON string)
DO $$ BEGIN
  ALTER TABLE profiles ADD COLUMN projects text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ═══════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY (RLS)
-- ═══════════════════════════════════════════════════════════════════

ALTER TABLE jobs           ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_apply_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_searches ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_notes      ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

-- Drop all existing policies first (clean slate)
DO $$ DECLARE r RECORD; BEGIN
  FOR r IN SELECT policyname, tablename FROM pg_policies
           WHERE schemaname = 'public'
           AND tablename IN ('jobs','profiles','auto_apply_log','saved_searches','job_notes','calendar_events')
  LOOP
    EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON ' || r.tablename;
  END LOOP;
END $$;

-- ── Jobs policies ─────────────────────────────────────────────────
CREATE POLICY "jobs_select" ON jobs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "jobs_insert" ON jobs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "jobs_update" ON jobs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "jobs_delete" ON jobs FOR DELETE USING (auth.uid() = user_id);

-- ── Profiles policies ─────────────────────────────────────────────
CREATE POLICY "profiles_select" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "profiles_delete" ON profiles FOR DELETE USING (auth.uid() = id);

-- ── Auto-apply log policies ───────────────────────────────────────
CREATE POLICY "apply_log_select" ON auto_apply_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "apply_log_insert" ON auto_apply_log FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "apply_log_update" ON auto_apply_log FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "apply_log_delete" ON auto_apply_log FOR DELETE USING (auth.uid() = user_id);

-- ── Saved searches policies ───────────────────────────────────────
CREATE POLICY "searches_select" ON saved_searches FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "searches_insert" ON saved_searches FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "searches_update" ON saved_searches FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "searches_delete" ON saved_searches FOR DELETE USING (auth.uid() = user_id);

-- ── Job notes policies ────────────────────────────────────────────
CREATE POLICY "notes_select" ON job_notes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notes_insert" ON job_notes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "notes_update" ON job_notes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "notes_delete" ON job_notes FOR DELETE USING (auth.uid() = user_id);

-- ── Calendar events policies ─────────────────────────────────────
CREATE POLICY "cal_select" ON calendar_events FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "cal_insert" ON calendar_events FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "cal_update" ON calendar_events FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "cal_delete" ON calendar_events FOR DELETE USING (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════════════════
-- INDEXES (for performance)
-- ═══════════════════════════════════════════════════════════════════

-- Jobs
CREATE INDEX IF NOT EXISTS idx_jobs_user_id     ON jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status       ON jobs(user_id, status);
CREATE INDEX IF NOT EXISTS idx_jobs_deadline     ON jobs(user_id, deadline) WHERE deadline IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_jobs_created      ON jobs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_match_score  ON jobs(user_id, match_score DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_auto_applied ON jobs(user_id, auto_applied) WHERE auto_applied = true;

-- Full-text search on jobs
CREATE INDEX IF NOT EXISTS idx_jobs_fts ON jobs
  USING gin(to_tsvector('english', coalesce(title,'') || ' ' || coalesce(company,'') || ' ' || coalesce(skills,'')));

-- Profiles
CREATE INDEX IF NOT EXISTS idx_profiles_id ON profiles(id);

-- Auto-apply log
CREATE INDEX IF NOT EXISTS idx_apply_log_user    ON auto_apply_log(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_apply_log_job     ON auto_apply_log(job_id);

-- Saved searches
CREATE INDEX IF NOT EXISTS idx_searches_user ON saved_searches(user_id, last_used DESC);

-- Job notes
CREATE INDEX IF NOT EXISTS idx_notes_job ON job_notes(job_id, created_at DESC);

-- Calendar events
CREATE INDEX IF NOT EXISTS idx_cal_user_date ON calendar_events(user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_cal_user_done ON calendar_events(user_id, is_done);
CREATE INDEX IF NOT EXISTS idx_cal_job_id    ON calendar_events(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cal_undone    ON calendar_events(user_id, event_date) WHERE is_done = false;

-- ═══════════════════════════════════════════════════════════════════
-- TRIGGERS (auto-update updated_at timestamps)
-- ═══════════════════════════════════════════════════════════════════

-- Generic updated_at trigger function
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

-- Apply to jobs
DROP TRIGGER IF EXISTS jobs_updated_at ON jobs;
CREATE TRIGGER jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Apply to profiles
DROP TRIGGER IF EXISTS profiles_updated_at ON profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ═══════════════════════════════════════════════════════════════════
-- FUNCTIONS (useful server-side helpers)
-- ═══════════════════════════════════════════════════════════════════

-- Get job statistics for the current user
CREATE OR REPLACE FUNCTION get_job_stats()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total',      COUNT(*),
    'bookmarked', COUNT(*) FILTER (WHERE status = 'Bookmarked'),
    'applied',    COUNT(*) FILTER (WHERE status = 'Applied'),
    'interview',  COUNT(*) FILTER (WHERE status = 'Interview'),
    'offer',      COUNT(*) FILTER (WHERE status = 'Offer'),
    'rejected',   COUNT(*) FILTER (WHERE status = 'Rejected'),
    'withdrawn',  COUNT(*) FILTER (WHERE status = 'Withdrawn'),
    'overdue',    COUNT(*) FILTER (WHERE deadline < CURRENT_DATE::text AND status NOT IN ('Rejected','Withdrawn','Offer')),
    'auto_applied', COUNT(*) FILTER (WHERE auto_applied = true),
    'high_priority', COUNT(*) FILTER (WHERE priority = 'High' AND status NOT IN ('Rejected','Withdrawn'))
  ) INTO result
  FROM jobs
  WHERE user_id = auth.uid();
  RETURN result;
END;
$$;

-- Full-text search on jobs
CREATE OR REPLACE FUNCTION search_jobs(query text)
RETURNS SETOF jobs LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY
    SELECT * FROM jobs
    WHERE user_id = auth.uid()
      AND to_tsvector('english', coalesce(title,'') || ' ' || coalesce(company,'') || ' ' || coalesce(skills,''))
          @@ plainto_tsquery('english', query)
    ORDER BY created_at DESC;
END;
$$;

-- Upsert profile (creates if not exists)
CREATE OR REPLACE FUNCTION upsert_profile(profile_data jsonb)
RETURNS profiles LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  result profiles;
BEGIN
  INSERT INTO profiles (id, updated_at)
  VALUES (auth.uid(), timezone('utc', now()))
  ON CONFLICT (id) DO NOTHING;

  UPDATE profiles
  SET
    full_name        = COALESCE((profile_data->>'full_name'), full_name),
    email            = COALESCE((profile_data->>'email'), email),
    phone            = COALESCE((profile_data->>'phone'), phone),
    location         = COALESCE((profile_data->>'location'), location),
    headline         = COALESCE((profile_data->>'headline'), headline),
    summary          = COALESCE((profile_data->>'summary'), summary),
    skills           = COALESCE((profile_data->>'skills'), skills),
    experience       = COALESCE((profile_data->>'experience'), experience),
    education        = COALESCE((profile_data->>'education'), education),
    certifications   = COALESCE((profile_data->>'certifications'), certifications),
    languages        = COALESCE((profile_data->>'languages'), languages),
    linkedin         = COALESCE((profile_data->>'linkedin'), linkedin),
    github           = COALESCE((profile_data->>'github'), github),
    portfolio        = COALESCE((profile_data->>'portfolio'), portfolio),
    target_roles     = COALESCE((profile_data->>'target_roles'), target_roles),
    target_locations = COALESCE((profile_data->>'target_locations'), target_locations),
    expected_salary  = COALESCE((profile_data->>'expected_salary'), expected_salary),
    resume_template  = COALESCE((profile_data->>'resume_template'), resume_template),
    updated_at       = timezone('utc', now())
  WHERE id = auth.uid()
  RETURNING * INTO result;

  RETURN result;
END;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- VIEWS (convenient read-only aggregates)
-- ═══════════════════════════════════════════════════════════════════

-- User dashboard view (joins jobs + profile stats)
CREATE OR REPLACE VIEW user_job_summary AS
SELECT
  j.user_id,
  COUNT(*)                                              AS total_jobs,
  COUNT(*) FILTER (WHERE j.status = 'Applied')          AS applied,
  COUNT(*) FILTER (WHERE j.status = 'Interview')        AS interviews,
  COUNT(*) FILTER (WHERE j.status = 'Offer')            AS offers,
  COUNT(*) FILTER (WHERE j.status = 'Rejected')         AS rejected,
  COUNT(*) FILTER (WHERE j.auto_applied = true)         AS auto_applied,
  COUNT(*) FILTER (WHERE j.deadline < CURRENT_DATE::text
    AND j.status NOT IN ('Rejected','Withdrawn','Offer')) AS overdue,
  MAX(j.created_at)                                     AS last_added
FROM jobs j
GROUP BY j.user_id;

-- Upcoming deadlines view
CREATE OR REPLACE VIEW upcoming_deadlines AS
SELECT
  j.*,
  (j.deadline::date - CURRENT_DATE) AS days_remaining
FROM jobs j
WHERE j.deadline IS NOT NULL
  AND j.deadline >= CURRENT_DATE::text
  AND j.deadline <= (CURRENT_DATE + INTERVAL '14 days')::text
  AND j.status NOT IN ('Rejected','Withdrawn','Offer')
ORDER BY j.deadline ASC;

-- ═══════════════════════════════════════════════════════════════════
-- STORAGE BUCKET (for resume file uploads)
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'resumes',
  'resumes',
  false,
  5242880,  -- 5MB limit
  ARRAY['application/pdf','text/plain','application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
ON CONFLICT (id) DO NOTHING;

-- RLS for resume storage (drop first so schema is re-runnable)
DROP POLICY IF EXISTS "resume_storage_select" ON storage.objects;
DROP POLICY IF EXISTS "resume_storage_insert" ON storage.objects;
DROP POLICY IF EXISTS "resume_storage_delete" ON storage.objects;

CREATE POLICY "resume_storage_select"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "resume_storage_insert"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "resume_storage_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'resumes' AND auth.uid()::text = (storage.foldername(name))[1]);

-- ═══════════════════════════════════════════════════════════════════
-- SEED: Demo data (optional — comment out in production)
-- Uncomment the block below to load sample jobs for testing
-- ═══════════════════════════════════════════════════════════════════

/*
-- Only inserts if the running user has no jobs yet
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM jobs WHERE user_id = auth.uid()) = 0 THEN
    INSERT INTO jobs (user_id, title, company, location, type, salary, skills, source, status, priority, notes)
    VALUES
      (auth.uid(), 'Software Engineer', 'Zoho Corp', 'Chennai, TN', 'Full-time', '₹8 LPA', 'React, Java, SQL', 'Naukri', 'Applied', 'High', 'Apply by March 31'),
      (auth.uid(), 'Data Analyst', 'Freshworks', 'Remote', 'Full-time', '₹6 LPA', 'Python, Tableau, SQL', 'LinkedIn', 'Interview', 'Medium', 'Round 2 scheduled'),
      (auth.uid(), 'Graduate Engineer Trainee', 'Aurolab', 'Madurai, TN', 'Full-time', '₹3 LPA', 'Python, AI/ML, Networking', 'Direct', 'Bookmarked', 'High', '2026 batch');
  END IF;
END $$;
*/

-- ═══════════════════════════════════════════════════════════════════
-- VERIFICATION QUERIES (run after applying schema to confirm setup)
-- ═══════════════════════════════════════════════════════════════════

/*
-- Check tables exist:
SELECT table_name, pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) AS size
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

-- Check RLS is enabled:
SELECT tablename, rowsecurity FROM pg_tables
WHERE schemaname = 'public' ORDER BY tablename;

-- Check indexes:
SELECT indexname, tablename FROM pg_indexes
WHERE schemaname = 'public' ORDER BY tablename, indexname;

-- Check policies:
SELECT policyname, tablename, cmd FROM pg_policies
WHERE schemaname = 'public' ORDER BY tablename, policyname;
*/
