-- ═══════════════════════════════════════════════════════════════════════════
-- JobBoard Pro — calendar_events table
-- Run this in Supabase → SQL Editor if the Calendar tab shows errors.
-- The Calendar.jsx component requires this table; it was missing from the
-- original supabase_schema.sql.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Table ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS calendar_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  title       text NOT NULL,
  event_date  text NOT NULL,          -- stored as YYYY-MM-DD text for simplicity
  event_time  text,                   -- stored as HH:MM (nullable)
  type        text DEFAULT 'reminder'
                CHECK (type IN ('deadline','interview','applied','offer','follow_up','reminder','other')),
  notes       text,
  is_done     boolean DEFAULT false
);

-- ─── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cal_select" ON calendar_events;
DROP POLICY IF EXISTS "cal_insert" ON calendar_events;
DROP POLICY IF EXISTS "cal_update" ON calendar_events;
DROP POLICY IF EXISTS "cal_delete" ON calendar_events;

CREATE POLICY "cal_select" ON calendar_events FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "cal_insert" ON calendar_events FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "cal_update" ON calendar_events FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "cal_delete" ON calendar_events FOR DELETE USING (auth.uid() = user_id);

-- ─── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_cal_user_date ON calendar_events(user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_cal_user_done ON calendar_events(user_id, is_done);
